### ISSUE TITLE
BertEmbedder doesn't seem to implement TextEmbedder

### ISSUE THREAD

**Issue by boswelja** [StarlightSearch/EmbedAnything#105]
**Describe the bug**

Attempting to use BERT as an embedding model seems to fail at compile time with a mismatched type exception, as `BertEmbedder` is not a `TextEmbedder`

**To Reproduce**

```rust
let embedder = Embedder::Text(BertEmbedder::new("sentence-transformers/all-MiniLM-L12-v2".into(), None).unwrap());
let embeddings = embed_file(file_name, &embedder, None, None).unwrap();
```

**Expected behavior**

I am able to use BertEmbedder successfully.

**Screenshots**

![image](https://github.com/user-attachments/assets/6b244f00-2ef7-4ba2-a0ca-b5d450271f68)

**Additional context**
It might be a good idea to verify all other embedders too, just to make sure their traits are correct

**Comment by akshayballal95** [comment]
The way it's implemented right now is that TextEmbedder is an enum, not a trait, and the different models are abstracted away using it. So, the right way to initialize a model is to use

``` rust
    let model =Embedder::Text(
        TextEmbedder::from_pretrained_hf("bert", "sentence-transformers/all-MiniLM-L12-v2", None)
            .unwrap(),
    );
```

This code will return an `Embedder` object.

**Comment by boswelja** [comment]
Oh interesting, I've been using `let embedder = Embedder::Text(TextEmbedder::Jina(Box::new(JinaEmbedder::default())));` for JINA, so I expected BERT to be the same :sweat_smile: 

Should these `new` functions be hidden from the public API, if the intention is to make users use `from` functions?

**Comment by akshayballal95** [comment]
Your Jina works because you are wrapping it in `TextEmbedder`. 

How do you suggest we abstract away the low-level API.

**Comment by boswelja** [comment]
> Your Jina works because you are wrapping it in TextEmbedder.

Oh I'm crazy, this is what I get for doing this late at night :sweat_smile: 

In that case, as it is now is probably fine? Looking at the `model: &str` in `from_pretrained_hf` it seems a little unintuitive having a finite set of options with freeform text input, but that's something I can address in my documentation adventure.
