### ISSUE TITLE
Support for Different Custom Models from OpenCLIP and Hugging Face for CLIP Encoder

### ISSUE THREAD

**Issue by cavitcakir** [StarlightSearch/EmbedAnything#37]
Hi,

I would like to request the addition of support for using different models from Hugging Face and our own OpenCLIP models for the CLIP encoder. Currently, the implementation is limited to 'vit_base_patch32', and expanding this to include other models from Hugging Face and our custom OpenCLIP models would significantly enhance the flexibility and usability of the library.

Thank you for considering this feature request. I believe it will greatly enhance the functionality and appeal of the project.

**Comment by sonam-pankaj95** [comment]
Thank you, @cavitcakir. It will be done by next week. You can add any custom model supported by Candle.

**Comment by akshayballal95** [comment]
The main branch now has support for models from Hugging face by just specifying a model id and revision. The wheels will be released after testing. But you can build from source if needed.
