### ISSUE TITLE
Add GPU Support for Embedding Pipeline

### ISSUE THREAD

**Issue by cavitcakir** [StarlightSearch/EmbedAnything#39]
Hi,

I would like to request the addition of GPU support for the embedding pipeline. Utilizing GPU for the embedding process can significantly speed up the computations compared to using CPU, thereby enhancing the performance and efficiency of the pipeline.

Thank you for considering this feature request. I believe it will greatly enhance the performance and flexibility of the project.

**Comment by akshayballal95** [comment]
Hey.. the GPU support is there now but I have been able to test it only with Rust. Need further testing with python.

**Comment by akshayballal95** [comment]
This is done now. You can use embed-anything-gpu now.
