### ISSUE TITLE
Split HTML parsing from website parsing

### ISSUE THREAD

**Issue by boswelja** [StarlightSearch/EmbedAnything#92]
It seems like this library is capable of parsing HTML, but right now it'll only allow you to do so through a URL.

It'd be cool if HTML parsing was something we could do separately, instead of requiring a URL and a web request!

**Comment by boswelja** [comment]
If this is something you're interested in adding, I'm happy to open a PR for the Rust side of things!

**Comment by akshayballal95** [comment]
Hey sure.. this is a good idea to parse downloaded documentation etc. Feel free to add an HTML processor in the `file_processor` module. 

You can open a PR. Also try to add an example use case. You can create a simple test HTM in test_files.
